#!/bin/bash
#Set the number to the appropriate GPU
export CUDA_VISIBLE_DEVICES=0

python simulationCmdStage.py
python simulationEquilPrepStage.py
python simulationEquilStage.py

python simulationProdStage.py
